姓名: Makefile CI

在……之上:
推:
分支机构: [分支："oneplus/sm8750_v_15.0.0_oneplus_13""oneplus/sm8750_v_15.0.0_oneplus_13"]"oneplus/sm8750_v_15.0.0_oneplus_13" ]
pull_request:
分支机构: [分支："oneplus/sm8750_v_15.0.0_oneplus_13""oneplus/sm8750_v_15.0.0_oneplus_13"]"oneplus/sm8750_v_15.0.0_oneplus_13" ]

工作:
建立:

run-on: 连续的:ubuntu-最新

步骤:
    - uses: 操作/结帐@v4

    - 姓名: 配置
跑: ./configure

    - 姓名: 安装相依性
跑: 使

    - 姓名: 运行检查
跑: 进行检查

    - 姓名: 运行distcheck
跑: 进行distcheck
